arduino, build_src_zip: trigger an error in case a file is not found

diff --git a/arduino/build_src_zip b/arduino/build_src_zip
--- a/arduino/build_src_zip
+++ b/arduino/build_src_zip
@@ -88,6 +88,7 @@ while read -r -u 9 line; do
     echo $line | grep -q "^#.*" && continue
     # Remove empty lines
     [ -z "$line" ] && continue
+    [ -n "$(ls $BASE/$line)" ] || { echo "$BASE/$line not found" ; exit 127 ; }
     for f in $(ls $BASE/$line) ; do
 	cp -a $f $SRCDIR
     done
